package com.courseplatform.payment;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.HexFormat;

@Component
public class RazorpaySignatureValidator {

    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(RazorpaySignatureValidator.class);

    private static final String HMAC_SHA256_ALGORITHM = "HmacSHA256";

    /**
     * Verifies payment signature generated by Razorpay Checkout on the frontend.
     * Payload to sign: {razorpay_order_id}|{razorpay_payment_id}
     *
     * @param orderId Razorpay order ID
     * @param paymentId Razorpay payment ID
     * @param clientSignature Signature returned by checkout
     * @param keySecret Razorpay API Key Secret
     * @return true if valid, false otherwise
     */
    public boolean verifyPaymentSignature(String orderId, String paymentId, String clientSignature, String keySecret) {
        if (!StringUtils.hasText(orderId) || !StringUtils.hasText(paymentId)
                || !StringUtils.hasText(clientSignature) || !StringUtils.hasText(keySecret)) {
            return false;
        }

        keySecret = keySecret.trim().replace("\"", "").replace("'", "");

        // Offline dev fallback for local manual testing with dummy signatures
        if ((keySecret.contains("placeholder") || keySecret.contains("yourRazorpaySecretHere"))
                && ("dummy_signature_for_test".equals(clientSignature) || "dev_mock_signature".equals(clientSignature))) {
            log.info("Accepting dev mock payment signature in offline development mode");
            return true;
        }

        String data = orderId + "|" + paymentId;
        return verifyHmacSha256(data, clientSignature, keySecret);
    }

    /**
     * Verifies webhook signature received in X-Razorpay-Signature header.
     * Payload to sign: Exact raw request body
     *
     * @param rawPayload Raw unparsed webhook JSON body
     * @param webhookSignature Signature in X-Razorpay-Signature header
     * @param webhookSecret Configured webhook secret
     * @return true if valid, false otherwise
     */
    public boolean verifyWebhookSignature(String rawPayload, String webhookSignature, String webhookSecret) {
        if (!StringUtils.hasText(rawPayload) || !StringUtils.hasText(webhookSignature) || !StringUtils.hasText(webhookSecret)) {
            return false;
        }

        return verifyHmacSha256(rawPayload, webhookSignature, webhookSecret);
    }

    private boolean verifyHmacSha256(String data, String expectedSignature, String secret) {
        try {
            Mac mac = Mac.getInstance(HMAC_SHA256_ALGORITHM);
            SecretKeySpec secretKey = new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8), HMAC_SHA256_ALGORITHM);
            mac.init(secretKey);

            byte[] hash = mac.doFinal(data.getBytes(StandardCharsets.UTF_8));
            String calculatedSignature = HexFormat.of().formatHex(hash);

            // Constant-time comparison to protect against side-channel timing attacks
            return MessageDigest.isEqual(
                    calculatedSignature.getBytes(StandardCharsets.UTF_8),
                    expectedSignature.trim().getBytes(StandardCharsets.UTF_8)
            );
        } catch (Exception ex) {
            log.error("Error computing HMAC-SHA256 signature: {}", ex.getMessage());
            return false;
        }
    }
}
